name: Build the IG
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SUSHI
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: sushi
      - name: Build Implementation Guide
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_genonce.sh -no-sushi
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
